version: "3"
services:
  app_react:
    build: ./front-end
    container_name: app_react
    env_file:
      - ./front-end/.env
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_node

  banco:
    image: postgres
    container_name: banco
    ports:
      - 2345:5432
    env_file:
      - ./back-end/.env.development
    volumes:
      - volume_banco:/var/lib/postgresql/data

  app_node:
    build: ./back-end
    container_name: app_node
    ports:
      - 4000:4000
    env_file:
      - ./back-end/.env.development
    volumes:
      - ./back-end:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://banco:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run start"
    depends_on:
      - banco

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:8080
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react

volumes:
  build_react:
  volume_banco: